### ISSUE TITLE
fix ferm rules

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/ansible-neofs-ir#60]

**Comment by aprasolova** [comment]
Duplicate the [firewall punches](https://github.com/nspcc-dev/ansible-neofs-ir/blob/master/defaults/main.yml#L91C1-L97C1) in VPN config

**Comment by aprasolova** [comment]
Use [this config](https://github.com/nspcc-dev/ansible-neogo-n3/blob/master/defaults/main.yml#L70C1-L77C1) for inspiration
